name: sawaid_assignment-$(Date:yyyMMdd)$(Rev:.r)

trigger:
  - none

variables:
  buildConfiguration: Release
  osImage: windows-latest
  websiteName: simplest_website_ever
  appPoolName: simplest_website_ever
  projectName: simplest_website_ever
  artifactName: dropping-bombs

pool:
  vmImage: $(osImage)

stages:
  - stage: build_stage
    displayName: Build Project
    jobs:
      - job: Build
        steps:
        - task: DotNetCoreCLI@2
          displayName: dotnet restore
          inputs:
            command: restore
            projects: "**/*.csproj"

        - task: DotNetCoreCLI@2
          displayName: dotnet build
          inputs:
            command: build
            projects: "**/*.csproj"
            arguments: --configuration $(buildConfiguration)

        - task: DotNetCoreCLI@2
          displayName: dotnet publish
          inputs:
            command: publish
            publishWebProjects: true
            arguments: -c $(buildConfiguration) -o $(build.ArtifactStagingDirectory)

        - task: PublishBuildArtifacts@1
          inputs:
            pathtoPublish: $(build.ArtifactStagingDirectory)
            ArtifactName: $(artifactName)
            publishLocation: Container
  - stage: dev_stage
    displayName: Deploying to Dev Environment
    jobs:
    - deployment: Dev
      displayName: Dev
      environment: 
        name: 'Dev'    
        resourceType: VirtualMachine
      variables:
      - name: websitePhysicalPath
        value: '%SystemDrive%\inetpub\wwwroot\$(websiteName)'

      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadBuildArtifacts@1
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: $(artifactName)
                downloadPath: '$(System.ArtifactStagingDirectory)'
            - task: IISWebAppManagementOnMachineGroup@0
              inputs:            
                IISDeploymentType: 'IISWebsite'
                ActionIISWebsite: 'CreateOrUpdateWebsite'
                WebsiteName: '$(websiteName)'
                WebsitePhysicalPath: '$(websitePhysicalPath)'
                WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
                CreateOrUpdateAppPoolForWebsite: true
                AppPoolNameForWebsite: '$(appPoolName)'
                DotNetVersionForWebsite: 'No Managed Code'
                PipeLineModeForWebsite: 'Integrated'
                AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
                AddBinding: true
                Bindings: |
                    {
                        bindings:[
                            {
                                "protocol":"http",
                                "ipAddress":"",
                                "hostname":"four-twenty",
                                "port":"420",
                                "sslThumbprint":"",
                                "sniFlag":false
                            }
                        ]
                    }
            - task: IISWebAppDeploymentOnMachineGroup@0
              inputs:
                WebSiteName: '$(websiteName)'
                Package: '$(System.DefaultWorkingDirectory)\**\*.zip'