name: sawaid_assignment-$(Date:yyyMMdd)$(Rev:.r)

trigger:
  - none

variables:
  buildConfiguration: Release
  osImage: windows-latest
  websiteName: simplest_website_ever

stages:
  - stage: build_stage
    displayName: Build Project
    jobs:
      - job: Build
        steps:
        - task: DotNetCoreCLI@2
          displayName: dotnet restore
          inputs:
            command: restore
            projects: "**/*.csproj"

        - task: DotNetCoreCLI@2
          displayName: dotnet build
          inputs:
            command: build
            projects: "**/*.csproj"
            arguments: --configuration $(buildConfiguration)

        - task: DotNetCoreCLI@2
          displayName: dotnet publish
          inputs:
            command: publish
            publishWebProjects: true
            arguments: -c $(buildConfiguration) -o $(build.ArtifactStagingDirectory)

        - task: PublishBuildArtifacts@1
          inputs:
            pathtoPublish: $(build.ArtifactStagingDirectory)
            ArtifactName: dropping-bombs
            publishLocation: Container
  - stage: dev_stage
    displayName: Download File
    jobs:
      - job: Develop
        steps:
          - task: DownloadBuildArtifacts@1
            displayName: Downloading File
            inputs:
              buildType: current
              downloadType: single
              artifactName: dropping-bombs
              downloadPath: $(System.AritfactsDirectory)
          - task: IISWebAppManagementOnMachineGroup@0
            displayName: IIS Web Application Manage
            inputs:
              EnableIIS: true
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: '$(websiteName)'
              WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: 'http/All Unassigned:69:sixty-nine'
          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'IIS Web App Deploy'
            inputs:
              WebSiteName: '$(websiteName)'
              TakeAppOfflineFlag: True
              XmlVariableSubstitution: True

